In [115]:
#Importamos las librerias necesarias para poder hacer la carga y la extraccion de datos a traves de la API airtable

import numpy as np
import pandas as pd

import requests
from pprint import pprint

import csv
from time import sleep

In [116]:
df = pd.read_csv("df.csv")

In [117]:
# En este codigo, vamos a explicar como cargar los datos de nuestro Dataframe en formato .json a la API de Airtable:

def cargar_airtable(df):
    
    df = df.replace(np.nan, None)
    
    #Aqui ponemos algunos detalles para hacer la  autenticación en Airtable
    API_KEY = 'pat6Mbqhjg0DDmAHT.3aba72e1d9691fe48dfaa3661e9cc047037606aa8d1bfa8b9f39194af5c8fe96'
    BASE_ID = 'appd8sa59m5s3Cisn'
    TABLE_ID= 'tblR6GQlWMKKebPBS'

    #La URL estará compuesta por la url principal, la BASE_ID y la TABLA_ID
    url = f'https://api.airtable.com/v0/{BASE_ID}/{TABLE_ID}'

    #Convierte el dataFrame creado del cv a un formato que se pueda enviar a la API de Airtable
    datos_json = datos_json = [{"fields" : df.iloc[i, :].to_dict()} for i in range(df.shape[0])]

    #Creamos el encabezado (headers) para crear una autorizacion a traves de nuestra API_KEY
    headers = {'Authorization': f'Bearer {API_KEY}',
               'Content-Type': 'application/json'}

    #Hacemos un bucle para ir cargando todos los datos de 10 en 10 en la API de Airtable
    
    for i in range(0, df.shape[0], 10):

        data = {"records" : datos_json[i : i + 10],
                "typecast" : True} #la variable data recoge un diccionario que incluye la parte de records y por otra parte los datos del json

        response = requests.post(url = url, json = data, headers = headers) #Hacemos requests para recibir la peticion de la API

        sleep(0.7) #Se hace sleep para no saturar la API

        if response.status_code == 200: #Si la respuesta es 200, los datos son cargados correctamente
            print("Se han cargado los datos a la API de Airtable")
        else: #Si la respuesta es distinta a 0, nos da un error en la carga de datos
            print(f"Error en la carga de datos: {response.text}")
            
    # return data

In [120]:
cargar_airtable(df)

Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable
Se han cargado los datos a la API de Airtable

In [121]:
# En este codigo, vamos a explicar como extraer los datos de la API de Airtable:

def extraer_airtable():

    #Aqui ponemos algunos detalles para hacer la  autenticación en Airtable
    API_KEY = 'pat6Mbqhjg0DDmAHT.3aba72e1d9691fe48dfaa3661e9cc047037606aa8d1bfa8b9f39194af5c8fe96'
    BASE_ID = 'appd8sa59m5s3Cisn'
    TABLE_ID = 'tblR6GQlWMKKebPBS'

    #La URL estará compuesta por la url principal, la BASE_ID y la TABLA ID
    url = f'https://api.airtable.com/v0/{BASE_ID}/{TABLE_ID}'

    #Creamos el encabezado (headers) para crear una autorizacion a traves de nuestra API_KEY
    headers = {'Authorization': f'Bearer {API_KEY}',
               'Content-Type': 'application/json'
    }
    #Con params, añadimos el parametro offset, para que no tengamos limitaciones a la hora de extraer datos
    params = {"offset" : None}

    df_download = pd.DataFrame() 

    #Usamos while para obtener extraer los datos de la API Airtable
    
    while params.get("offset") != None or df_download.shape[0] == 0:

        response = requests.get(url, headers = headers, params = params) #Hacemos requests para recibir la peticion de la API

        if response.status_code == 200: #Si la respuesta es 200, los datos son descargados correctamente
            print("Se ha realizado la descarga completa de los datos")

        params["offset"] = response.json().get("offset") #Añadimos el parametro offset para eliminar la limitacion de extraer datos

        print(params.get("offset"))

        df_download = pd.concat([df_download, pd.json_normalize(response.json()["records"])], ignore_index = True) #Hacemos concdenacion de los archivos descargados, normalizando los archivos json e ignorando los indices de nuestra descarga.

        # sleep(0.7) #Se hace sleep para no saturar la API
        
    return df_download #Devuelve los archivos que estamos descargando

In [122]:
#Con esto devolvemos el archivo descargado en un DataFrame
df_download = extraer_airtable()

df_download

Se ha realizado la descarga completa de los datos
itr4dHEswl6jJ14VH/recFBcwav3lOjORK7
Se ha realizado la descarga completa de los datos
itr4dHEswl6jJ14VH/recS8eV8j8CEIDwvt
Se ha realizado la descarga completa de los datos
itr4dHEswl6jJ14VH/reck5UsO2SHdeNYKS
Se ha realizado la descarga completa de los datos
itr4dHEswl6jJ14VH/recyNEBGuT3VIeVku
Se ha realizado la descarga completa de los datos
None

,id,createdTime,fields.Provincia,fields.Nombre,fields.Latitud,fields.Longitud,fields.Year,fields.Tmed_min,fields.Tmed_year,fields.Tmed_max,fields.Dias<0º,fields.Dias>30º,fields.Hum relativa,fields.Precipitacion,fields.Lluvia
0,rec0CrwLbwYr6gkiP,2024-01-11T20:17:56.000Z,SALAMANCA,SALAMANCA AEROPUERTO,405734N,052954W,1993,4.90,11.08,17.24,91,42,66.42,411.3,118
1,rec0IgrLsx718F3RZ,2024-01-11T20:18:20.000Z,VALENCIA,VALENCIA AEROPUERTO,392906N,002829W,2012,12.68,18.42,24.13,10,80,53.64,419.6,61
2,rec0LnHL5neorPbsM,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2010,10.82,16.28,21.68,15,46,70.42,559.6,113
3,rec0gGTvzFPySWwM7,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2009,11.41,17.01,22.52,5,74,69.83,557.3,111
4,rec0rEWe1lUjL1uvs,2024-01-11T20:17:22.000Z,BARCELONA,BARCELONA AEROPUERTO,411734N,020412E,1992,10.35,14.76,19.13,4,3,NaN,534.7,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,recyO7r6PojYfiwST,2024-01-11T20:18:19.000Z,VALENCIA,VALENCIA AEROPUERTO,392906N,002829W,2001,13.45,18.56,23.63,3,66,64.33,505.9,72
401,recySUBkpPbx5N2Jz,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2018,11.91,17.44,22.92,7,83,69.83,451.2,105
402,recz37UhnjhpKkEjY,2024-01-11T20:17:26.000Z,BARCELONA,BARCELONA AEROPUERTO,411734N,020412E,2022,14.97,18.92,22.79,0,66,67.55,331.8,76
403,reczmY1j1eyseMDaw,2024-01-11T20:17:29.000Z,BIZKAIA,BILBAO AEROPUERTO,431753N,025423W,1995,9.88,15.05,20.15,8,13,71.75,1033.0,187
404,reczvUy5r1haEHkrR,2024-01-11T20:17:36.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,1989,11.16,17.08,22.98,10,61,74.00,345.7,93

In [123]:
df_download.columns = [x.split(".")[1] if "." in x else x for x in df_download.columns]

df_download

,id,createdTime,Provincia,Nombre,Latitud,Longitud,Year,Tmed_min,Tmed_year,Tmed_max,Dias<0º,Dias>30º,Hum relativa,Precipitacion,Lluvia
0,rec0CrwLbwYr6gkiP,2024-01-11T20:17:56.000Z,SALAMANCA,SALAMANCA AEROPUERTO,405734N,052954W,1993,4.90,11.08,17.24,91,42,66.42,411.3,118
1,rec0IgrLsx718F3RZ,2024-01-11T20:18:20.000Z,VALENCIA,VALENCIA AEROPUERTO,392906N,002829W,2012,12.68,18.42,24.13,10,80,53.64,419.6,61
2,rec0LnHL5neorPbsM,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2010,10.82,16.28,21.68,15,46,70.42,559.6,113
3,rec0gGTvzFPySWwM7,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2009,11.41,17.01,22.52,5,74,69.83,557.3,111
4,rec0rEWe1lUjL1uvs,2024-01-11T20:17:22.000Z,BARCELONA,BARCELONA AEROPUERTO,411734N,020412E,1992,10.35,14.76,19.13,4,3,NaN,534.7,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,recyO7r6PojYfiwST,2024-01-11T20:18:19.000Z,VALENCIA,VALENCIA AEROPUERTO,392906N,002829W,2001,13.45,18.56,23.63,3,66,64.33,505.9,72
401,recySUBkpPbx5N2Jz,2024-01-11T20:17:39.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,2018,11.91,17.44,22.92,7,83,69.83,451.2,105
402,recz37UhnjhpKkEjY,2024-01-11T20:17:26.000Z,BARCELONA,BARCELONA AEROPUERTO,411734N,020412E,2022,14.97,18.92,22.79,0,66,67.55,331.8,76
403,reczmY1j1eyseMDaw,2024-01-11T20:17:29.000Z,BIZKAIA,BILBAO AEROPUERTO,431753N,025423W,1995,9.88,15.05,20.15,8,13,71.75,1033.0,187
404,reczvUy5r1haEHkrR,2024-01-11T20:17:36.000Z,ILLES BALEARS,"PALMA DE MALLORCA, AEROPUERTO",393339N,024412E,1989,11.16,17.08,22.98,10,61,74.00,345.7,93